branch-defaults:
  ebs:
    environment: ItemDetails-env
    group_suffix: null
  master:
    environment: node-express-env
    group_suffix: null
environment-defaults:
  ItemDetails-env:
    branch: null
    repository: null
  node-express-env:
    branch: null
    repository: null
global:
  application_name: item-details
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
