version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.11.1
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: test
          command: npm run test
      
