version: 2
jobs:
  client:
    docker:
      - image: circleci/node:9.11.1
      
      working_directory: ~/spec
      
    steps:
      - run: npm install
      
      -save_cache:
       paths: 
        - node_modules
              
      - run: npm run test
