 version: 2
 jobs:
   client:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Client tests"
       - run: sleep 25
   server:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: echo "Server tests"
       - run: sleep 15
 workflows:
   version: 2
   client_and_server:
     jobs:
       - client
       - server
