version: 2
jobs:
  client:
    docker:
      - image: circleci/node:9.11.1
      - image: circleci/mongoose: 5.6.10
      
      working_directory: ~/spec
      
    steps:
      - run: npm install
      
      -save_cache:
       paths: 
        - node_modules
        
      - run: npm run seed
      
      - run: npm run test
