[
	{
		"itemId": 1,
		"point1": "Molestiae odit ullam amet laudantium cupiditate excepturi quo id et.",
		"point2": "Ut aut ullam quo.",
		"point3": "Eaque aspernatur est totam atque consequuntur aut.",
		"point4": "Consequatur ut sed.",
		"point5": null,
		"blurb": "Suscipit et beatae quo beatae id aut eius. Aliquid nisi voluptatem animi porro maiores quos blanditiis rerum. Ut eos quis est est laboriosam rerum molestias. Laboriosam omnis dolor officia amet enim occaecati. Ut accusamus nemo perferendis vel tempore repellendus. Officiis voluptatum maxime iusto voluptate odio cupiditate molestiae dolores quia.",
		"sizing": "invoice",
		"material": "Wooden",
		"fit": "Intelligent",
		"length": "neural",
		"features": "Intelligent",
		"neckline": "Practical",
		"itemStyle": "Ergonomic",
		"garmentCuffCutType": "Cape Small Cotton Gloves Incredible",
		"garmentSleeveStyle": "calculate Ohio",
		"careAndCleaning": "purple withdrawal Reactive",
		"TCIN": 21876,
		"UPC": 31057,
		"DPCI": 11744,
		"origin": "Harbors",
		"recycledPolyester": true,
		"fastShipping": false,
		"estimatedShipDimensions": "Deserunt repellat esse explicabo nulla et occaecati eos iste.",
		"estimatedShipWeight": "bandwidth",
		"type": "Men - Shirts"
	},
	{
		"itemId": 2,
		"point1": null,
		"point2": null,
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Sapiente alias et accusantium ea est ad qui. Deserunt cupiditate officiis veritatis error. Nostrum alias id hic a.",
		"sizing": "salmon",
		"material": "Plastic",
		"fit": "Refined",
		"length": "reinvent",
		"features": "Intelligent",
		"neckline": "Intelligent",
		"itemStyle": "Handcrafted",
		"garmentCuffCutType": "XML Louisiana",
		"garmentSleeveStyle": "Tuna",
		"careAndCleaning": "invoice",
		"TCIN": 88910,
		"UPC": 4037,
		"DPCI": 69661,
		"origin": "open-source",
		"recycledPolyester": true,
		"fastShipping": false,
		"estimatedShipDimensions": "Optio eligendi delectus quam illo accusamus.",
		"estimatedShipWeight": "non-volatile",
		"type": "Men - Shirts"
	},
	{
		"itemId": 3,
		"point1": null,
		"point2": null,
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Assumenda saepe sit quia sit itaque ab non sunt. Corrupti maiores et. Numquam corrupti eligendi quo quod molestias ratione dolor ipsum. Dolor omnis ut rerum. Officia sequi corrupti.",
		"sizing": "Supervisor",
		"material": "Rubber",
		"fit": "Fantastic",
		"length": "eyeballs Investment Account Music",
		"features": "Gorgeous",
		"neckline": "Refined",
		"itemStyle": "Handcrafted",
		"garmentCuffCutType": "killer",
		"garmentSleeveStyle": "Buckinghamshire",
		"careAndCleaning": "Nevada",
		"TCIN": 66288,
		"UPC": 91216,
		"DPCI": 65044,
		"origin": "Dominica",
		"recycledPolyester": false,
		"fastShipping": false,
		"estimatedShipDimensions": "Quo aut pariatur nobis dolor et libero incidunt magnam.",
		"estimatedShipWeight": "PCI quantifying",
		"type": "Men - Shirts"
	},
	{
		"itemId": 4,
		"point1": "Eius fugiat illo tempora ullam.",
		"point2": "Qui et laudantium porro sapiente maiores deserunt officiis est et.",
		"point3": "Itaque quis molestias ab a qui quia dolor.",
		"point4": "Deleniti est eveniet ratione sit id aliquam sed.",
		"point5": null,
		"blurb": "Eius corrupti magni a ut maiores sit voluptatem. Dolores corporis laborum porro. Iure voluptate dolorem eos excepturi est. Saepe et ipsum est libero distinctio voluptatem quasi omnis. Totam quibusdam officia magni impedit. Consectetur rem dolorum quod labore aliquam sed nostrum dolor.",
		"sizing": "sky blue",
		"material": "Metal",
		"fit": "Awesome",
		"length": "mint green Granite wireless",
		"features": "Awesome",
		"neckline": "Handmade",
		"itemStyle": "Tasty",
		"garmentCuffCutType": "French Polynesia Wooden",
		"garmentSleeveStyle": "Manager",
		"careAndCleaning": "Manager virtual",
		"TCIN": 77288,
		"UPC": 64506,
		"DPCI": 81859,
		"origin": "Inverse",
		"recycledPolyester": true,
		"fastShipping": false,
		"estimatedShipDimensions": "Aut consequatur perferendis praesentium aut perspiciatis.",
		"estimatedShipWeight": "Arizona Fresh Steel",
		"type": "Men - Shirts"
	},
	{
		"itemId": 5,
		"point1": "Laborum quia qui et vero debitis nisi.",
		"point2": "Nobis dignissimos magnam temporibus temporibus aliquam consequuntur sed.",
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Eveniet molestiae placeat at ratione nesciunt. Veritatis repudiandae aut error accusamus ad aperiam quisquam ab et. Possimus quod voluptas repellendus magnam corrupti alias et et sed.",
		"sizing": "Cambridgeshire",
		"material": "Concrete",
		"fit": "Tasty",
		"length": "Convertible Marks Avon",
		"features": "Generic",
		"neckline": "Incredible",
		"itemStyle": "Small",
		"garmentCuffCutType": "bypassing Bedfordshire Security",
		"garmentSleeveStyle": "partnerships",
		"careAndCleaning": "fuchsia Refined",
		"TCIN": 42101,
		"UPC": 7361,
		"DPCI": 27372,
		"origin": "instruction set",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Voluptatem non voluptate maiores eaque modi alias laboriosam ex.",
		"estimatedShipWeight": "primary Cheese Chair",
		"type": "Men - Shirts"
	},
	{
		"itemId": 6,
		"point1": "Qui dolorem velit.",
		"point2": "Sunt voluptas omnis iure id nostrum asperiores.",
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Omnis vel saepe fugit. Similique minima optio. Vero voluptatibus enim ut impedit occaecati illo doloribus. Nobis cum voluptate aperiam quaerat perferendis qui autem at. Enim ea porro aut et sunt dolor aliquid facere.",
		"sizing": "Savings Account",
		"material": "Cotton",
		"fit": "Small",
		"length": "Product",
		"features": "Awesome",
		"neckline": "Generic",
		"itemStyle": "Ergonomic",
		"garmentCuffCutType": "capacitor turquoise cyan",
		"garmentSleeveStyle": "Singapore Gourde US Dollar Investment Account",
		"careAndCleaning": "Assistant Avon",
		"TCIN": 3290,
		"UPC": 78081,
		"DPCI": 55421,
		"origin": "Handcrafted",
		"recycledPolyester": true,
		"fastShipping": false,
		"estimatedShipDimensions": "Laborum et dolore omnis consequatur culpa et qui repudiandae.",
		"estimatedShipWeight": "Tactics Handmade",
		"type": "Men - Shirts"
	},
	{
		"itemId": 7,
		"point1": "Pariatur odit provident ut saepe accusantium veritatis.",
		"point2": "Voluptatem beatae accusamus sunt quis quia beatae ducimus sit.",
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Quaerat eaque molestias et. Necessitatibus qui molestiae in quia ipsa accusantium doloribus. Ad expedita sed eum pariatur nisi. Ad dolorum aperiam sit enim et necessitatibus delectus harum quis.",
		"sizing": "compress",
		"material": "Plastic",
		"fit": "Gorgeous",
		"length": "Malawi Mountain",
		"features": "Sleek",
		"neckline": "Unbranded",
		"itemStyle": "Intelligent",
		"garmentCuffCutType": "workforce France Senior",
		"garmentSleeveStyle": "mesh Assistant invoice",
		"careAndCleaning": "Soap green",
		"TCIN": 74764,
		"UPC": 65922,
		"DPCI": 25984,
		"origin": "calculating",
		"recycledPolyester": true,
		"fastShipping": true,
		"estimatedShipDimensions": "Quis officiis tempora quisquam a.",
		"estimatedShipWeight": "algorithm",
		"type": "Men - Shirts"
	},
	{
		"itemId": 8,
		"point1": "Assumenda omnis laudantium vel.",
		"point2": "Error et ut sed quam ut.",
		"point3": "Blanditiis eos vero nemo consequatur enim et et aut eum.",
		"point4": null,
		"point5": null,
		"blurb": "Exercitationem eum dolore voluptate inventore assumenda quo velit. Autem earum consequatur. Eum esse hic. Animi qui amet. Praesentium tempore praesentium sunt rerum quas ab. Praesentium quasi voluptas voluptatem quae ut sit.",
		"sizing": "disintermediate",
		"material": "Soft",
		"fit": "Practical",
		"length": "Program Coordinator neural",
		"features": "Fantastic",
		"neckline": "Awesome",
		"itemStyle": "Sleek",
		"garmentCuffCutType": "Manager COM Applications",
		"garmentSleeveStyle": "Customer transmitter AGP",
		"careAndCleaning": "quantifying Hawaii",
		"TCIN": 21466,
		"UPC": 87533,
		"DPCI": 79850,
		"origin": "calculating",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Error placeat illo eius.",
		"estimatedShipWeight": "Liaison parallelism",
		"type": "Men - Shirts"
	},
	{
		"itemId": 9,
		"point1": "Mollitia quo commodi consequatur neque.",
		"point2": "Eum illo dolorem et dolores ex sed reprehenderit ratione.",
		"point3": "Magnam neque iste nobis.",
		"point4": "Est id ratione tempora illum quia nisi excepturi.",
		"point5": null,
		"blurb": "Distinctio consequatur et dolore cupiditate et. Nihil dolor sunt et. Assumenda omnis rerum et minus aliquid sunt vitae.",
		"sizing": "Usability",
		"material": "Cotton",
		"fit": "Incredible",
		"length": "Coordinator invoice",
		"features": "Fantastic",
		"neckline": "Practical",
		"itemStyle": "Licensed",
		"garmentCuffCutType": "Applications",
		"garmentSleeveStyle": "Small Frozen Bacon override Intelligent Soft Ball",
		"careAndCleaning": "Courts Concrete invoice",
		"TCIN": 98147,
		"UPC": 51767,
		"DPCI": 88259,
		"origin": "calculate",
		"recycledPolyester": true,
		"fastShipping": false,
		"estimatedShipDimensions": "Odit vero qui rerum ut.",
		"estimatedShipWeight": "Pants",
		"type": "Men - Shirts"
	},
	{
		"itemId": 10,
		"point1": "Repellat dolore facere.",
		"point2": "Quo error velit repudiandae distinctio velit ea.",
		"point3": "Blanditiis blanditiis sint ut sed.",
		"point4": null,
		"point5": null,
		"blurb": "Quis saepe eaque praesentium repellat fugit soluta expedita. Autem iste eum. Eaque quidem eos. Ullam enim id eveniet.",
		"sizing": "Grocery",
		"material": "Metal",
		"fit": "Generic",
		"length": "Functionality Buckinghamshire",
		"features": "Fantastic",
		"neckline": "Handcrafted",
		"itemStyle": "Rustic",
		"garmentCuffCutType": "Zambia",
		"garmentSleeveStyle": "port virtual installation",
		"careAndCleaning": "invoice CFA Franc BEAC tan",
		"TCIN": 89856,
		"UPC": 99173,
		"DPCI": 66365,
		"origin": "International",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Ex sed iure dolores dolores.",
		"estimatedShipWeight": "platforms synthesizing",
		"type": "Men - Shirts"
	}
]