[
	{
		"itemId": 1,
		"point1": "Sit est possimus rem.",
		"point2": "Occaecati consequuntur molestiae vitae error quasi.",
		"point3": "Nesciunt ipsam aut dignissimos.",
		"point4": "Sit veniam rerum.",
		"point5": null,
		"blurb": "Et aperiam repellat. Omnis et et non nobis. Odio et et ut distinctio dignissimos velit deserunt sint. Ex et ratione autem. Ex ratione et facere voluptates incidunt consequatur necessitatibus et molestiae. Pariatur distinctio facere.",
		"sizing": "ivory",
		"material": "Granite",
		"fit": "Generic",
		"length": "grey port",
		"features": "Licensed",
		"neckline": "Refined",
		"itemStyle": "Tasty",
		"garmentCuffCutType": "approach bypassing Creative",
		"garmentSleeveStyle": "deposit Table Strategist",
		"careAndCleaning": "Fresh Corners Trail",
		"TCIN": 70054,
		"UPC": 24435,
		"DPCI": 45388,
		"origin": "card",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Et suscipit aut aspernatur ea.",
		"estimatedShipWeight": "Kansas optimize",
		"type": "Men - Shirts"
	},
	{
		"itemId": 2,
		"point1": "Voluptate accusantium sit incidunt.",
		"point2": "Ut occaecati id quo et fugiat.",
		"point3": "Quidem laborum voluptatem assumenda maxime qui optio.",
		"point4": "Laborum eum fugiat corrupti commodi natus eos sunt culpa quam.",
		"point5": "Unde debitis veniam voluptatum similique.",
		"blurb": "Unde laboriosam accusamus. Et sunt eveniet quidem. Reprehenderit aliquam magni molestiae. Assumenda dolor molestiae magnam doloremque. Voluptatem eum minima aperiam reprehenderit aliquid mollitia omnis et. Qui dicta at harum dicta ex dolor quibusdam velit eos.",
		"sizing": "communities",
		"material": "Plastic",
		"fit": "Handcrafted",
		"length": "Sleek Table Ergonomic Fresh Sausages",
		"features": "Sleek",
		"neckline": "Intelligent",
		"itemStyle": "Rustic",
		"garmentCuffCutType": "China Officer communities",
		"garmentSleeveStyle": "navigate",
		"careAndCleaning": "Gloves",
		"TCIN": 73906,
		"UPC": 62999,
		"DPCI": 67833,
		"origin": "backing up",
		"recycledPolyester": false,
		"fastShipping": false,
		"estimatedShipDimensions": "Error quod rerum earum ut quisquam sed.",
		"estimatedShipWeight": "black",
		"type": "Men - Shirts"
	},
	{
		"itemId": 3,
		"point1": null,
		"point2": null,
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Omnis expedita eos harum rerum molestias fugit. Autem quidem accusantium optio quisquam doloribus et est voluptates. Totam eum qui. Magni porro ipsum cupiditate autem.",
		"sizing": "Kentucky",
		"material": "Fresh",
		"fit": "Fantastic",
		"length": "violet Generic Concrete Hat interface",
		"features": "Gorgeous",
		"neckline": "Practical",
		"itemStyle": "Intelligent",
		"garmentCuffCutType": "Buckinghamshire feed Savings Account",
		"garmentSleeveStyle": "Industrial",
		"careAndCleaning": "Wisconsin",
		"TCIN": 32708,
		"UPC": 7930,
		"DPCI": 34837,
		"origin": "sky blue",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Omnis fuga et officiis doloribus quia odio aut et accusamus.",
		"estimatedShipWeight": "Automotive payment ROI",
		"type": "Men - Shirts"
	},
	{
		"itemId": 4,
		"point1": null,
		"point2": null,
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Officia molestiae sapiente. Officia nihil nesciunt reprehenderit aspernatur nam ab perferendis possimus. Ut sint nostrum omnis vitae eum saepe.",
		"sizing": "Egyptian Pound",
		"material": "Soft",
		"fit": "Gorgeous",
		"length": "wireless Frozen",
		"features": "Fantastic",
		"neckline": "Fantastic",
		"itemStyle": "Licensed",
		"garmentCuffCutType": "technologies",
		"garmentSleeveStyle": "Cotton",
		"careAndCleaning": "blue Auto Loan Account B2C",
		"TCIN": 79269,
		"UPC": 77589,
		"DPCI": 83057,
		"origin": "Azerbaijan",
		"recycledPolyester": true,
		"fastShipping": true,
		"estimatedShipDimensions": "Maxime quisquam similique fugiat libero numquam voluptatum adipisci similique corrupti.",
		"estimatedShipWeight": "Savings Account",
		"type": "Men - Shirts"
	},
	{
		"itemId": 5,
		"point1": "Maiores molestias facilis blanditiis fuga.",
		"point2": "Corrupti et harum distinctio quisquam est sit aut.",
		"point3": "Animi minus eum enim quaerat delectus ipsam beatae.",
		"point4": null,
		"point5": null,
		"blurb": "Rerum et et sapiente dolorum ipsa veniam. Aliquam dolorum quia eaque sit eum. Et ex ducimus id magni. Alias unde neque laboriosam. Corrupti recusandae rem quia impedit dolores aut id officiis inventore. Voluptate veniam dolor cumque.",
		"sizing": "Brand",
		"material": "Granite",
		"fit": "Intelligent",
		"length": "Administrator Berkshire",
		"features": "Tasty",
		"neckline": "Refined",
		"itemStyle": "Incredible",
		"garmentCuffCutType": "optical Home Loan Account",
		"garmentSleeveStyle": "Small Concrete Chair markets Books",
		"careAndCleaning": "payment Steel",
		"TCIN": 98790,
		"UPC": 20206,
		"DPCI": 52210,
		"origin": "Guernsey",
		"recycledPolyester": false,
		"fastShipping": false,
		"estimatedShipDimensions": "In consequuntur laudantium rerum eveniet id.",
		"estimatedShipWeight": "1080p",
		"type": "Men - Shirts"
	},
	{
		"itemId": 6,
		"point1": null,
		"point2": null,
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Eligendi provident at consequatur doloribus. Labore ut minus illo minus dolor enim mollitia est eum. Voluptates quibusdam eos. Est ipsam aut temporibus adipisci et vel. Eaque provident dolor.",
		"sizing": "Branding",
		"material": "Plastic",
		"fit": "Sleek",
		"length": "Investment Account web-readiness bandwidth",
		"features": "Incredible",
		"neckline": "Refined",
		"itemStyle": "Small",
		"garmentCuffCutType": "Keys needs-based",
		"garmentSleeveStyle": "web-enabled bricks-and-clicks scalable",
		"careAndCleaning": "Infrastructure e-business",
		"TCIN": 98277,
		"UPC": 73251,
		"DPCI": 41777,
		"origin": "target",
		"recycledPolyester": false,
		"fastShipping": false,
		"estimatedShipDimensions": "Nesciunt repellat molestias vel expedita sint.",
		"estimatedShipWeight": "tan COM overriding",
		"type": "Men - Shirts"
	},
	{
		"itemId": 7,
		"point1": "Ea consectetur et.",
		"point2": "Facilis quis necessitatibus.",
		"point3": "Fuga ut minima perferendis voluptatem ab impedit qui sunt voluptatem.",
		"point4": "Maxime dolores autem voluptates ex eum quam est quibusdam.",
		"point5": "Illum atque nam dolorem minima.",
		"blurb": "Eius vero aliquid repudiandae autem qui quia et. Beatae et voluptatem quas doloribus facilis magnam debitis. Repudiandae aut harum dolor. Reiciendis dolorum animi nemo.",
		"sizing": "District",
		"material": "Frozen",
		"fit": "Awesome",
		"length": "SMS",
		"features": "Handcrafted",
		"neckline": "Intelligent",
		"itemStyle": "Intelligent",
		"garmentCuffCutType": "wireless e-business Gibraltar",
		"garmentSleeveStyle": "ivory Saudi Riyal",
		"careAndCleaning": "Brunei Dollar Bouvet Island (Bouvetoya) payment",
		"TCIN": 7663,
		"UPC": 44211,
		"DPCI": 70644,
		"origin": "azure",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Pariatur quo officia possimus.",
		"estimatedShipWeight": "embrace Grocery",
		"type": "Men - Shirts"
	},
	{
		"itemId": 8,
		"point1": "Consequatur quaerat magnam eaque dicta.",
		"point2": "Beatae a aut quaerat provident id aut est qui.",
		"point3": "Quia fuga velit.",
		"point4": "Alias et voluptate.",
		"point5": "Commodi omnis veritatis.",
		"blurb": "Ea non iure sed. Sed quia sequi voluptates aut eos voluptatem magnam. Libero unde temporibus. A dolorem nulla. Eos pariatur dicta.",
		"sizing": "wireless",
		"material": "Metal",
		"fit": "Intelligent",
		"length": "orange Gorgeous",
		"features": "Rustic",
		"neckline": "Handmade",
		"itemStyle": "Refined",
		"garmentCuffCutType": "fuchsia South Dakota",
		"garmentSleeveStyle": "Incredible Plastic Ball 24/7 Metal",
		"careAndCleaning": "Gateway Kentucky",
		"TCIN": 74167,
		"UPC": 83883,
		"DPCI": 15477,
		"origin": "Rubber",
		"recycledPolyester": false,
		"fastShipping": true,
		"estimatedShipDimensions": "Nam quis natus sed tenetur dolorum aut.",
		"estimatedShipWeight": "HTTP Moldovan Leu",
		"type": "Men - Shirts"
	},
	{
		"itemId": 9,
		"point1": null,
		"point2": null,
		"point3": null,
		"point4": null,
		"point5": null,
		"blurb": "Quos quia minima dolore quibusdam voluptatem. Excepturi quos consequatur asperiores dolore eaque. Enim iure qui.",
		"sizing": "South Dakota",
		"material": "Soft",
		"fit": "Licensed",
		"length": "Saint Helena Pound optical indigo",
		"features": "Intelligent",
		"neckline": "Handcrafted",
		"itemStyle": "Rustic",
		"garmentCuffCutType": "embrace Executive",
		"garmentSleeveStyle": "Tasty Regional",
		"careAndCleaning": "deposit Vermont Facilitator",
		"TCIN": 11442,
		"UPC": 97479,
		"DPCI": 3674,
		"origin": "generate",
		"recycledPolyester": true,
		"fastShipping": true,
		"estimatedShipDimensions": "Consequatur sed eum praesentium minus quae ratione optio exercitationem nesciunt.",
		"estimatedShipWeight": "Security",
		"type": "Men - Shirts"
	},
	{
		"itemId": 10,
		"point1": "Aut eos ipsum doloremque non incidunt dolor sed in eos.",
		"point2": "Rerum nihil earum et ut optio accusamus nulla.",
		"point3": "Voluptas odit eius omnis expedita nisi aliquam deserunt molestias.",
		"point4": "Quos quae quibusdam.",
		"point5": "Omnis mollitia aliquid rerum.",
		"blurb": "Natus ullam maxime est illum placeat et. Ut tenetur ut sit et optio qui consequatur. Qui dicta accusantium. Aut voluptates voluptatem nihil aut perspiciatis qui sed atque. Et est tempore pariatur. Vel ipsum et nulla assumenda iure atque doloribus ex.",
		"sizing": "Awesome",
		"material": "Metal",
		"fit": "Tasty",
		"length": "input dynamic Frozen",
		"features": "Intelligent",
		"neckline": "Gorgeous",
		"itemStyle": "Fantastic",
		"garmentCuffCutType": "Managed",
		"garmentSleeveStyle": "Rubber User-centric Concrete",
		"careAndCleaning": "mission-critical",
		"TCIN": 7382,
		"UPC": 99558,
		"DPCI": 52812,
		"origin": "intermediate",
		"recycledPolyester": true,
		"fastShipping": false,
		"estimatedShipDimensions": "Iste quos eligendi culpa et aspernatur dicta numquam.",
		"estimatedShipWeight": "Executive Kids Metal",
		"type": "Men - Shirts"
	}
]